name: Rust test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docs
        run: cargo doc --all-features
      - name: Run tests
        run: cargo test
      - name: Run all features tests
        run: cargo test --all-features
      - name: Run clippy
        run: cargo clippy -- -D warnings
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install miri
        run: rustup component add --toolchain nightly miri

      - name: Run miri
        run: cargo +nightly miri test
      - name: Run all features miri
        run: cargo +nightly miri test --all-features

