name: Rust test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docs
        run: cargo doc
      - name: Run tests
        run: cargo test
      - name: Run no default features tests
        run: cargo test --no-default-features
      - name: Run all features tests
        run: cargo test --all-features
      - name: Run clippy
        run: cargo clippy -- -D warnings

